# Generated by Django 4.0.5 on 2022-07-17 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='web_id',
            field=models.CharField(help_text='format: required, unique', max_length=100, unique=True, verbose_name='product website ID'),
        ),
    ]
